# Generated by Django 4.2.2 on 2023-06-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("twitterclon", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(default="default.png", upload_to=""),
        ),
    ]
