# Generated by Django 4.2.2 on 2023-06-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("twitterclon", "0004_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(default="default.png", upload_to=""),
        ),
    ]
